name: Build Mirai-MCPing

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew build
      - name: Release Mirai-MCPing
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: "Mirai-MCPing v1.2-Beta"
          automatic_release_tag: "1.2"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: "build/libs"
          prerelease: false
